[package]
name = "Hakurei-Backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
base64 = "0.21.7"
# serde = { version = "1.0", features = ["derive"] }
